version: '3'

services:

  contract:
    build: 
      context: enigma-contract
      args:
        - SSH_PRIVATE_KEY
        - GIT_BRANCH_CONTRACT=${GIT_BRANCH_CONTRACT}
    stdin_open: true
    tty: true

  surface:
    build: 
      context: surface
      args:
        - SSH_PRIVATE_KEY
        - GIT_BRANCH_SURFACE=${GIT_BRANCH_SURFACE}
        - GIT_BRANCH_CONTRACT=${GIT_BRANCH_CONTRACT}
    stdin_open: true
    tty: true
